language: c++
dist: trusty
sudo: required

notifications:
  email: false

matrix:
  include:
  - os: linux
    compiler: g++
    env: COMPILER=g++-4.9

  - os: osx
    osx_image: xcode7.3

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release
  - cd ../
